version: "3"
services:
  app:
    image: 3dx_app
    build: ./
    depends_on:
      - database
    ports:
      - 8082:4000
    networks:
      - webapp-network
  database:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./src/db:/app/db
    networks:
      - webapp-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=super # 默认开启授权，并创建超管用户 mongo -u godis -p godis@admin --authenticationDatabase admin
      - MONGO_INITDB_ROOT_PASSWORD=3dx # 超管密码，敏感数据也可以使用 `secrets`，不赘述。
      - MONGO_INITDB_DATABASE=3dx # *.js 中默认的数据库
networks:
  webapp-network:
    driver: bridge
